object MAINF: TMAINF
  Left = -8
  Top = -8
  AutoScroll = False
  BorderIcons = []
  ClientHeight = 718
  ClientWidth = 1024
  Color = 14540253
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  WindowState = wsMaximized
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 13
  object Label1: TLabel
    Left = 173
    Top = 9
    Width = 676
    Height = 52
    Alignment = taCenter
    AutoSize = False
    Caption = 'MOTOR  TESTER'
    Color = clLime
    Font.Charset = ANSI_CHARSET
    Font.Color = clBlack
    Font.Height = -37
    Font.Name = 'Arial'
    Font.Style = [fsBold, fsItalic]
    ParentColor = False
    ParentFont = False
    Layout = tlCenter
  end
  object Label11: TLabel
    Left = 521
    Top = 641
    Width = 156
    Height = 84
    Alignment = taCenter
    AutoSize = False
    Color = clYellow
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = '±¼¸²Ã¼'
    Font.Style = [fsBold]
    ParentColor = False
    ParentFont = False
    Layout = tlCenter
  end
  object Label12: TLabel
    Left = 692
    Top = 641
    Width = 156
    Height = 84
    Alignment = taCenter
    AutoSize = False
    Color = clYellow
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = '±¼¸²Ã¼'
    Font.Style = [fsBold]
    ParentColor = False
    ParentFont = False
    Layout = tlCenter
  end
  object Label13: TLabel
    Left = 864
    Top = 641
    Width = 156
    Height = 84
    Alignment = taCenter
    AutoSize = False
    Color = clYellow
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = '±¼¸²Ã¼'
    Font.Style = [fsBold]
    ParentColor = False
    ParentFont = False
    Layout = tlCenter
  end
  object setup_btn: TLabel
    Left = 524
    Top = 644
    Width = 150
    Height = 79
    Alignment = taCenter
    AutoSize = False
    Caption = 'SETUP'
    Color = clSilver
    Font.Charset = ANSI_CHARSET
    Font.Color = clBlack
    Font.Height = -29
    Font.Name = 'µ¸¿ò'
    Font.Style = [fsBold]
    ParentColor = False
    ParentFont = False
    Layout = tlCenter
    OnClick = setup_btnClick
  end
  object data_btn: TLabel
    Left = 695
    Top = 644
    Width = 150
    Height = 79
    Alignment = taCenter
    AutoSize = False
    Caption = 'DATA'
    Color = clSilver
    Font.Charset = ANSI_CHARSET
    Font.Color = clBlack
    Font.Height = -29
    Font.Name = 'µ¸¿ò'
    Font.Style = [fsBold]
    ParentColor = False
    ParentFont = False
    Layout = tlCenter
    OnClick = data_btnClick
  end
  object exit_btn: TLabel
    Left = 867
    Top = 644
    Width = 150
    Height = 79
    Alignment = taCenter
    AutoSize = False
    Caption = 'EXIT'
    Color = clSilver
    Font.Charset = ANSI_CHARSET
    Font.Color = clBlack
    Font.Height = -29
    Font.Name = 'µ¸¿ò'
    Font.Style = [fsBold]
    ParentColor = False
    ParentFont = False
    Layout = tlCenter
    OnClick = exit_btnClick
  end
  object Label3: TLabel
    Left = 6
    Top = 641
    Width = 156
    Height = 84
    Alignment = taCenter
    AutoSize = False
    Color = clYellow
    Font.Charset = ANSI_CHARSET
    Font.Color = clBlack
    Font.Height = -29
    Font.Name = '±¼¸²'
    Font.Style = [fsBold]
    ParentColor = False
    ParentFont = False
    Layout = tlCenter
  end
  object model_btn: TLabel
    Left = 9
    Top = 644
    Width = 150
    Height = 79
    Alignment = taCenter
    AutoSize = False
    Caption = 'MODEL'
    Color = clSilver
    Font.Charset = ANSI_CHARSET
    Font.Color = clBlack
    Font.Height = -29
    Font.Name = 'µ¸¿ò'
    Font.Style = [fsBold]
    ParentColor = False
    ParentFont = False
    Layout = tlCenter
    OnClick = model_btnClick
  end
  object punct_result_label: TLabel
    Left = 260
    Top = 650
    Width = 10
    Height = 1
    Alignment = taCenter
    AutoSize = False
    Color = clYellow
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'MS Serif'
    Font.Style = [fsBold]
    ParentColor = False
    ParentFont = False
    Layout = tlCenter
    Visible = False
  end
  object Label47: TLabel
    Left = 8
    Top = 573
    Width = 131
    Height = 50
    Alignment = taCenter
    AutoSize = False
    Caption = 'MODEL'
    Color = clTeal
    Font.Charset = ANSI_CHARSET
    Font.Color = clWhite
    Font.Height = -24
    Font.Name = 'µ¸¿ò'
    Font.Style = [fsBold]
    ParentColor = False
    ParentFont = False
    Layout = tlCenter
  end
  object MODEL_LABEL: TLabel
    Left = 145
    Top = 575
    Width = 353
    Height = 47
    Alignment = taCenter
    AutoSize = False
    Caption = 'A1'
    Color = clPurple
    Font.Charset = ANSI_CHARSET
    Font.Color = clWhite
    Font.Height = -35
    Font.Name = '±¼¸²Ã¼'
    Font.Style = [fsBold]
    ParentColor = False
    ParentFont = False
    Layout = tlCenter
  end
  object total_result_label: TLabel
    Left = 637
    Top = 526
    Width = 308
    Height = 96
    Alignment = taCenter
    AutoSize = False
    Caption = 'READY'
    Color = clYellow
    Font.Charset = ANSI_CHARSET
    Font.Color = clBlack
    Font.Height = -37
    Font.Name = '±¼¸²'
    Font.Style = [fsBold]
    ParentColor = False
    ParentFont = False
    Layout = tlCenter
  end
  object Label5: TLabel
    Left = 263
    Top = 531
    Width = 10
    Height = 1
    Alignment = taCenter
    AutoSize = False
    Color = clYellow
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'MS Serif'
    Font.Style = [fsBold]
    ParentColor = False
    ParentFont = False
    Layout = tlCenter
    Visible = False
  end
  object Label24: TLabel
    Left = 103
    Top = 516
    Width = 10
    Height = 1
    Alignment = taCenter
    AutoSize = False
    Color = clYellow
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'MS Serif'
    Font.Style = [fsBold]
    ParentColor = False
    ParentFont = False
    Layout = tlCenter
    Visible = False
  end
  object Label25: TLabel
    Left = 8
    Top = 474
    Width = 166
    Height = 86
    Alignment = taCenter
    AutoSize = False
    Color = clTeal
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = '±¼¸²'
    Font.Style = [fsBold]
    ParentColor = False
    ParentFont = False
    Layout = tlCenter
  end
  object Label28: TLabel
    Left = 614
    Top = 437
    Width = 162
    Height = 40
    Alignment = taCenter
    AutoSize = False
    Caption = 'TOTAL'
    Color = clSilver
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = '±¼¸²'
    Font.Style = [fsBold]
    ParentColor = False
    ParentFont = False
    Layout = tlCenter
    Visible = False
  end
  object Label29: TLabel
    Left = 798
    Top = 435
    Width = 162
    Height = 40
    Alignment = taCenter
    AutoSize = False
    Caption = 'N G'
    Color = clSilver
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = '±¼¸²'
    Font.Style = [fsBold]
    ParentColor = False
    ParentFont = False
    Layout = tlCenter
    Visible = False
  end
  object Label35: TLabel
    Left = 10
    Top = 476
    Width = 162
    Height = 40
    Alignment = taCenter
    AutoSize = False
    Caption = 'COUNT'
    Color = clSilver
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = '±¼¸²'
    Font.Style = [fsBold]
    ParentColor = False
    ParentFont = False
    Layout = tlCenter
  end
  object total_count_label: TLabel
    Left = 616
    Top = 591
    Width = 162
    Height = 40
    Alignment = taCenter
    AutoSize = False
    Caption = '0'
    Color = clWhite
    Font.Charset = ANSI_CHARSET
    Font.Color = clBlack
    Font.Height = -16
    Font.Name = '±¼¸²'
    Font.Style = [fsBold]
    ParentColor = False
    ParentFont = False
    Layout = tlCenter
    Visible = False
  end
  object ok_count_label: TLabel
    Left = 10
    Top = 518
    Width = 162
    Height = 40
    Alignment = taCenter
    AutoSize = False
    Caption = '0'
    Color = clWhite
    Font.Charset = ANSI_CHARSET
    Font.Color = clBlue
    Font.Height = -16
    Font.Name = '±¼¸²'
    Font.Style = [fsBold]
    ParentColor = False
    ParentFont = False
    Layout = tlCenter
  end
  object ng_count_label: TLabel
    Left = 802
    Top = 596
    Width = 162
    Height = 40
    Alignment = taCenter
    AutoSize = False
    Caption = '0'
    Color = clWhite
    Font.Charset = ANSI_CHARSET
    Font.Color = clRed
    Font.Height = -16
    Font.Name = '±¼¸²'
    Font.Style = [fsBold]
    ParentColor = False
    ParentFont = False
    Layout = tlCenter
    Visible = False
  end
  object Label30: TLabel
    Left = 178
    Top = 641
    Width = 156
    Height = 84
    Alignment = taCenter
    AutoSize = False
    Color = clYellow
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = '±¼¸²Ã¼'
    Font.Style = [fsBold]
    ParentColor = False
    ParentFont = False
    Layout = tlCenter
  end
  object auto_btn: TLabel
    Left = 181
    Top = 644
    Width = 150
    Height = 79
    Alignment = taCenter
    AutoSize = False
    Caption = 'AUTO'
    Color = clSilver
    Font.Charset = ANSI_CHARSET
    Font.Color = clBlack
    Font.Height = -29
    Font.Name = 'µ¸¿ò'
    Font.Style = [fsBold]
    ParentColor = False
    ParentFont = False
    Layout = tlCenter
    OnClick = auto_btnClick
  end
  object Label32: TLabel
    Left = 349
    Top = 641
    Width = 156
    Height = 84
    Alignment = taCenter
    AutoSize = False
    Color = clYellow
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = '±¼¸²Ã¼'
    Font.Style = [fsBold]
    ParentColor = False
    ParentFont = False
    Layout = tlCenter
  end
  object manual_btn: TLabel
    Left = 352
    Top = 644
    Width = 150
    Height = 79
    Alignment = taCenter
    AutoSize = False
    Caption = 'MANUAL'
    Color = clSilver
    Font.Charset = ANSI_CHARSET
    Font.Color = clBlack
    Font.Height = -29
    Font.Name = 'µ¸¿ò'
    Font.Style = [fsBold]
    ParentColor = False
    ParentFont = False
    Layout = tlCenter
    OnClick = manual_btnClick
  end
  object GroupBox1: TGroupBox
    Left = 571
    Top = 76
    Width = 220
    Height = 388
    TabOrder = 0
    object Label4: TLabel
      Left = 6
      Top = 13
      Width = 206
      Height = 40
      Alignment = taCenter
      AutoSize = False
      Caption = 'INSULATION TEST'
      Color = clTeal
      Font.Charset = ANSI_CHARSET
      Font.Color = clWhite
      Font.Height = -21
      Font.Name = 'µ¸¿òÃ¼'
      Font.Style = [fsBold]
      ParentColor = False
      ParentFont = False
      Layout = tlCenter
    end
    object Label6: TLabel
      Left = 44
      Top = 316
      Width = 135
      Height = 63
      Alignment = taCenter
      AutoSize = False
      Caption = 'RESET'
      Color = clWhite
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -35
      Font.Name = '±¼¸²'
      Font.Style = [fsBold]
      ParentColor = False
      ParentFont = False
      Layout = tlCenter
    end
    object insulation_test_btn: TLabel
      Left = 47
      Top = 319
      Width = 129
      Height = 57
      Alignment = taCenter
      AutoSize = False
      Caption = 'TEST'
      Color = clTeal
      Font.Charset = ANSI_CHARSET
      Font.Color = clWhite
      Font.Height = -35
      Font.Name = '±¼¸²'
      Font.Style = [fsBold]
      ParentColor = False
      ParentFont = False
      Layout = tlCenter
      OnClick = insulation_test_btnClick
    end
    object insulation_result: TLabel
      Left = 47
      Top = 240
      Width = 129
      Height = 59
      Alignment = taCenter
      AutoSize = False
      Caption = 'O K'
      Color = clLime
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -35
      Font.Name = '±¼¸²'
      Font.Style = [fsBold]
      ParentColor = False
      ParentFont = False
      Layout = tlCenter
    end
    object Label16: TLabel
      Left = 9
      Top = 60
      Width = 201
      Height = 160
      Alignment = taCenter
      AutoSize = False
      Color = clBlack
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = '±¼¸²'
      Font.Style = [fsBold]
      ParentColor = False
      ParentFont = False
      Layout = tlCenter
    end
    object Label17: TLabel
      Left = 10
      Top = 61
      Width = 199
      Height = 158
      Alignment = taCenter
      AutoSize = False
      Caption = 'DC 500 ( Vdc )'#13#10#13#10'100 ( M§Ù ) ¡è'
      Color = clSilver
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = '±¼¸²'
      Font.Style = [fsBold]
      ParentColor = False
      ParentFont = False
      Layout = tlCenter
    end
  end
  object GroupBox2: TGroupBox
    Left = 9
    Top = 76
    Width = 549
    Height = 388
    TabOrder = 1
    object Label9: TLabel
      Left = 6
      Top = 14
      Width = 536
      Height = 40
      Alignment = taCenter
      AutoSize = False
      Caption = 'POWER TEST'
      Color = clTeal
      Font.Charset = ANSI_CHARSET
      Font.Color = clWhite
      Font.Height = -21
      Font.Name = 'µ¸¿òÃ¼'
      Font.Style = [fsBold]
      ParentColor = False
      ParentFont = False
      Layout = tlCenter
    end
    object Label7: TLabel
      Left = 126
      Top = 316
      Width = 135
      Height = 63
      Alignment = taCenter
      AutoSize = False
      Caption = 'RESET'
      Color = clWhite
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -35
      Font.Name = '±¼¸²'
      Font.Style = [fsBold]
      ParentColor = False
      ParentFont = False
      Layout = tlCenter
    end
    object power_result: TLabel
      Left = 312
      Top = 317
      Width = 129
      Height = 59
      Alignment = taCenter
      AutoSize = False
      Caption = 'O K'
      Color = clLime
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -35
      Font.Name = '±¼¸²'
      Font.Style = [fsBold]
      ParentColor = False
      ParentFont = False
      Layout = tlCenter
    end
    object Label42: TLabel
      Left = 8
      Top = 59
      Width = 532
      Height = 247
      Alignment = taCenter
      AutoSize = False
      Color = clBlack
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'MS Serif'
      Font.Style = [fsBold]
      ParentColor = False
      ParentFont = False
      Layout = tlCenter
    end
    object Label92: TLabel
      Left = 9
      Top = 60
      Width = 147
      Height = 40
      Alignment = taCenter
      AutoSize = False
      Caption = 'No.'
      Color = clSilver
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = '±¼¸²'
      Font.Style = [fsBold]
      ParentColor = False
      ParentFont = False
      Layout = tlCenter
    end
    object Label43: TLabel
      Left = 157
      Top = 60
      Width = 127
      Height = 40
      Alignment = taCenter
      AutoSize = False
      Caption = 'HI'
      Color = clSilver
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = '±¼¸²'
      Font.Style = [fsBold]
      ParentColor = False
      ParentFont = False
      Layout = tlCenter
    end
    object Label44: TLabel
      Left = 285
      Top = 60
      Width = 126
      Height = 40
      Alignment = taCenter
      AutoSize = False
      Caption = 'MEAS'
      Color = clSilver
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = '±¼¸²'
      Font.Style = [fsBold]
      ParentColor = False
      ParentFont = False
      Layout = tlCenter
    end
    object Label45: TLabel
      Left = 412
      Top = 60
      Width = 127
      Height = 40
      Alignment = taCenter
      AutoSize = False
      Caption = 'LO'
      Color = clSilver
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = '±¼¸²'
      Font.Style = [fsBold]
      ParentColor = False
      ParentFont = False
      Layout = tlCenter
    end
    object Label22: TLabel
      Left = 9
      Top = 101
      Width = 147
      Height = 40
      Alignment = taCenter
      AutoSize = False
      Caption = ' CURRENT-1 ( A )'
      Color = clSilver
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = '±¼¸²'
      Font.Style = [fsBold]
      ParentColor = False
      ParentFont = False
      Layout = tlCenter
    end
    object Label26: TLabel
      Left = 9
      Top = 142
      Width = 147
      Height = 40
      Alignment = taCenter
      AutoSize = False
      Caption = ' SPEED-1 ( RPM )'
      Color = clSilver
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = '±¼¸²'
      Font.Style = [fsBold]
      ParentColor = False
      ParentFont = False
      Layout = tlCenter
    end
    object Label27: TLabel
      Left = 9
      Top = 183
      Width = 147
      Height = 40
      Alignment = taCenter
      AutoSize = False
      Caption = ' CURRENT-2 ( A )'
      Color = clSilver
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = '±¼¸²'
      Font.Style = [fsBold]
      ParentColor = False
      ParentFont = False
      Layout = tlCenter
    end
    object power_test_btn: TLabel
      Left = 129
      Top = 319
      Width = 129
      Height = 57
      Alignment = taCenter
      AutoSize = False
      Caption = 'TEST'
      Color = clTeal
      Font.Charset = ANSI_CHARSET
      Font.Color = clWhite
      Font.Height = -35
      Font.Name = '±¼¸²'
      Font.Style = [fsBold]
      ParentColor = False
      ParentFont = False
      Layout = tlCenter
      OnClick = power_test_btnClick
    end
    object Label8: TLabel
      Left = 9
      Top = 224
      Width = 147
      Height = 40
      Alignment = taCenter
      AutoSize = False
      Caption = ' SPEED-2 ( RPM )'
      Color = clSilver
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = '±¼¸²'
      Font.Style = [fsBold]
      ParentColor = False
      ParentFont = False
      Layout = tlCenter
    end
    object Label10: TLabel
      Left = 9
      Top = 265
      Width = 147
      Height = 40
      Alignment = taCenter
      AutoSize = False
      Caption = 'ROTATE'
      Color = clSilver
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = '±¼¸²'
      Font.Style = [fsBold]
      ParentColor = False
      ParentFont = False
      Layout = tlCenter
    end
    object pwsg: THyperGrid
      Left = 156
      Top = 99
      Width = 383
      Height = 206
      Color = clWhite
      ColCount = 4
      DefaultColWidth = 106
      DefaultRowHeight = 40
      DefaultDrawing = False
      Enabled = False
      FixedColor = clWhite
      FixedCols = 3
      FixedRows = 0
      Font.Charset = HANGEUL_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = '±¼¸²Ã¼'
      Font.Style = []
      ParentFont = False
      ScrollBars = ssNone
      TabOrder = 0
      Columns = <
        item
          Name = 'Column 2'
          TitleColor = clWhite
          TitleFont.Charset = HANGEUL_CHARSET
          TitleFont.Color = clBlack
          TitleFont.Height = -16
          TitleFont.Name = '±¼¸²'
          TitleFont.Style = [fsBold]
          TitleParentFont = False
          TitleClipStyle = hgclpEllipsis
          TitleOuterBevel = bvNone
          ColumnHAlignment = taCenter
          ColumnVAlignment = hgvaCenter
          ColumnColor = clWhite
          ColumnFont.Charset = HANGEUL_CHARSET
          ColumnFont.Color = clWindowText
          ColumnFont.Height = -13
          ColumnFont.Name = '±¼¸²'
          ColumnFont.Style = [fsBold]
          ColumnParentFont = False
        end
        item
          Name = 'Column 3'
          TitleColor = clWhite
          TitleFont.Charset = HANGEUL_CHARSET
          TitleFont.Color = clBlue
          TitleFont.Height = -16
          TitleFont.Name = '±¼¸²'
          TitleFont.Style = [fsBold]
          TitleParentFont = False
          TitleClipStyle = hgclpEllipsis
          TitleOuterBevel = bvNone
          ColumnHAlignment = taCenter
          ColumnVAlignment = hgvaCenter
          ColumnFont.Charset = HANGEUL_CHARSET
          ColumnFont.Color = clWindowText
          ColumnFont.Height = -13
          ColumnFont.Name = '±¼¸²'
          ColumnFont.Style = [fsBold]
          ColumnParentFont = False
        end
        item
          Name = 'Column 4'
          TitleColor = clWhite
          TitleFont.Charset = HANGEUL_CHARSET
          TitleFont.Color = clWindowText
          TitleFont.Height = -16
          TitleFont.Name = '±¼¸²'
          TitleFont.Style = [fsBold]
          TitleParentFont = False
          TitleClipStyle = hgclpEllipsis
          TitleOuterBevel = bvNone
          ColumnHAlignment = taCenter
          ColumnVAlignment = hgvaCenter
          ColumnFont.Charset = HANGEUL_CHARSET
          ColumnFont.Color = clWindowText
          ColumnFont.Height = -13
          ColumnFont.Name = '±¼¸²'
          ColumnFont.Style = [fsBold]
          ColumnParentFont = False
        end
        item
          Name = 'Column 5'
        end>
      Headings = <>
      HyperOptions = []
      HyperHighlightColor = clWhite
      HyperHighlightFontColor = clWhite
      AVisibleColumnCount = 4
      ColWidths = (
        126
        126
        126
        142)
      RowHeights = (
        40
        40
        40
        40
        40)
    end
  end
  object GroupBox3: TGroupBox
    Left = 796
    Top = 76
    Width = 220
    Height = 388
    TabOrder = 2
    object Label2: TLabel
      Left = 6
      Top = 13
      Width = 206
      Height = 40
      Alignment = taCenter
      AutoSize = False
      Caption = 'PUNCTURE TEST'
      Color = clTeal
      Font.Charset = ANSI_CHARSET
      Font.Color = clWhite
      Font.Height = -21
      Font.Name = 'µ¸¿òÃ¼'
      Font.Style = [fsBold]
      ParentColor = False
      ParentFont = False
      Layout = tlCenter
    end
    object Label18: TLabel
      Left = 9
      Top = 60
      Width = 201
      Height = 160
      Alignment = taCenter
      AutoSize = False
      Color = clBlack
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = '±¼¸²'
      Font.Style = [fsBold]
      ParentColor = False
      ParentFont = False
      Layout = tlCenter
    end
    object Label19: TLabel
      Left = 10
      Top = 61
      Width = 199
      Height = 158
      Alignment = taCenter
      AutoSize = False
      Caption = 'AC 1.8 kV ( Vrms )'#13#10#13#10'2.5 ( mA ) ¡é'
      Color = clSilver
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = '±¼¸²'
      Font.Style = [fsBold]
      ParentColor = False
      ParentFont = False
      Layout = tlCenter
    end
    object puncture_result: TLabel
      Left = 48
      Top = 240
      Width = 129
      Height = 59
      Alignment = taCenter
      AutoSize = False
      Caption = 'O K'
      Color = clLime
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -35
      Font.Name = '±¼¸²'
      Font.Style = [fsBold]
      ParentColor = False
      ParentFont = False
      Layout = tlCenter
    end
    object Label23: TLabel
      Left = 44
      Top = 316
      Width = 135
      Height = 63
      Alignment = taCenter
      AutoSize = False
      Caption = 'RESET'
      Color = clWhite
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -35
      Font.Name = '±¼¸²'
      Font.Style = [fsBold]
      ParentColor = False
      ParentFont = False
      Layout = tlCenter
    end
    object puncture_test_btn: TLabel
      Left = 47
      Top = 319
      Width = 129
      Height = 57
      Alignment = taCenter
      AutoSize = False
      Caption = 'TEST'
      Color = clTeal
      Font.Charset = ANSI_CHARSET
      Font.Color = clWhite
      Font.Height = -35
      Font.Name = '±¼¸²'
      Font.Style = [fsBold]
      ParentColor = False
      ParentFont = False
      Layout = tlCenter
      OnClick = puncture_test_btnClick
    end
  end
  object m_f_time: TTimer
    Enabled = False
    OnTimer = m_f_timeTimer
    Left = 52
    Top = 15
  end
  object com1: TComPort
    BaudRate = br38400
    Port = 'COM1'
    Parity.Bits = prNone
    Parity.Check = False
    Parity.Replace = False
    Parity.ReplaceChar = #0
    StopBits = sbOneStopBit
    DataBits = dbEight
    DiscardNull = False
    EventChar = #0
    Events = [evRxChar]
    Buffer.InputSize = 128
    Buffer.OutputSize = 128
    FlowControl.FlowControl = fcNone
    FlowControl.OutCTSFlow = False
    FlowControl.OutDSRFlow = False
    FlowControl.ControlDTR = dtrDisable
    FlowControl.ControlRTS = rtsDisable
    FlowControl.XonXoffOut = False
    FlowControl.XonXoffIn = False
    FlowControl.DSRSensitivity = False
    FlowControl.TxContinueOnXoff = False
    FlowControl.XonChar = #17
    FlowControl.XoffChar = #19
    Timeouts.ReadInterval = 100
    Timeouts.ReadTotalMultiplier = 100
    Timeouts.ReadTotalConstant = 500
    Timeouts.WriteTotalMultiplier = 100
    Timeouts.WriteTotalConstant = 500
    SyncMethod = smWindowSync
    OnRxChar = com1RxChar
    Left = 14
    Top = 12
  end
  object com2: TComPort
    BaudRate = br38400
    Port = 'COM2'
    Parity.Bits = prNone
    Parity.Check = False
    Parity.Replace = False
    Parity.ReplaceChar = #0
    StopBits = sbOneStopBit
    DataBits = dbEight
    DiscardNull = False
    EventChar = #0
    Events = []
    Buffer.InputSize = 1024
    Buffer.OutputSize = 128
    FlowControl.FlowControl = fcNone
    FlowControl.OutCTSFlow = False
    FlowControl.OutDSRFlow = False
    FlowControl.ControlDTR = dtrDisable
    FlowControl.ControlRTS = rtsDisable
    FlowControl.XonXoffOut = False
    FlowControl.XonXoffIn = False
    FlowControl.DSRSensitivity = False
    FlowControl.TxContinueOnXoff = False
    FlowControl.XonChar = #17
    FlowControl.XoffChar = #19
    Timeouts.ReadInterval = 200
    Timeouts.ReadTotalMultiplier = 100
    Timeouts.ReadTotalConstant = 500
    Timeouts.WriteTotalMultiplier = 100
    Timeouts.WriteTotalConstant = 500
    SyncMethod = smWindowSync
    Left = 13
    Top = 44
  end
  object sp_reset: TTimer
    Enabled = False
    Interval = 10
    OnTimer = sp_resetTimer
    Left = 128
    Top = 22
  end
  object sp_start: TTimer
    Enabled = False
    Interval = 10
    OnTimer = sp_startTimer
    Left = 92
    Top = 24
  end
  object power_meas_timer: TTimer
    Enabled = False
    Interval = 10
    OnTimer = power_meas_timerTimer
    Left = 61
    Top = 47
  end
  object insul_meas_timer: TTimer
    Enabled = False
    OnTimer = insul_meas_timerTimer
    Left = 112
    Top = 33
  end
  object punct_meas_timer: TTimer
    Enabled = False
    OnTimer = punct_meas_timerTimer
    Left = 112
    Top = 33
  end
  object step_timer1: TTimer
    Enabled = False
    Interval = 300
    OnTimer = step_timer1Timer
    Left = 200
    Top = 18
  end
  object step_timer2: TTimer
    Enabled = False
    Interval = 300
    OnTimer = step_timer2Timer
    Left = 200
    Top = 18
  end
  object step_timer3: TTimer
    Enabled = False
    Interval = 300
    OnTimer = step_timer3Timer
    Left = 200
    Top = 18
  end
  object step_timer4: TTimer
    Enabled = False
    Interval = 300
    OnTimer = step_timer4Timer
    Left = 200
    Top = 18
  end
  object power_auto_time: TTimer
    Enabled = False
    Interval = 3000
    OnTimer = power_auto_timeTimer
    Left = 239
    Top = 22
  end
  object clear_time: TTimer
    Enabled = False
    Interval = 10
    OnTimer = clear_timeTimer
    Left = 281
    Top = 30
  end
  object daytime: TTimer
    Enabled = False
    Interval = 10
    OnTimer = daytimeTimer
    Left = 30
    Top = 14
  end
  object power_auto_time2: TTimer
    Enabled = False
    Interval = 3000
    OnTimer = power_auto_time2Timer
    Left = 239
    Top = 22
  end
  object com4: TComPort
    BaudRate = br9600
    Port = 'COM4'
    Parity.Bits = prNone
    Parity.Check = False
    Parity.Replace = False
    Parity.ReplaceChar = #0
    StopBits = sbOneStopBit
    DataBits = dbEight
    DiscardNull = False
    EventChar = #0
    Events = []
    Buffer.InputSize = 1024
    Buffer.OutputSize = 128
    FlowControl.FlowControl = fcNone
    FlowControl.OutCTSFlow = False
    FlowControl.OutDSRFlow = False
    FlowControl.ControlDTR = dtrDisable
    FlowControl.ControlRTS = rtsDisable
    FlowControl.XonXoffOut = False
    FlowControl.XonXoffIn = False
    FlowControl.DSRSensitivity = False
    FlowControl.TxContinueOnXoff = False
    FlowControl.XonChar = #17
    FlowControl.XoffChar = #19
    Timeouts.ReadInterval = 200
    Timeouts.ReadTotalMultiplier = 100
    Timeouts.ReadTotalConstant = 500
    Timeouts.WriteTotalMultiplier = 100
    Timeouts.WriteTotalConstant = 500
    SyncMethod = smWindowSync
    Left = 13
    Top = 44
  end
end
